items:
- uid: System.Reflection.TargetParameterCountException
  commentId: T:System.Reflection.TargetParameterCountException
  id: TargetParameterCountException
  parent: System.Reflection
  children:
  - System.Reflection.TargetParameterCountException.#ctor
  - System.Reflection.TargetParameterCountException.#ctor(System.String)
  - System.Reflection.TargetParameterCountException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: TargetParameterCountException
  fullName: System.Reflection.TargetParameterCountException
  type: Class
  source:
    remote:
      path: src/System.Reflection/ref/4.0/System.Reflection.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: TargetParameterCountException
    path: src/System.Reflection/ref/4.0/System.Reflection.cs
    startLine: 273
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: "\n<p>The exception that is thrown when the number of parameters for an invocation does not match the number expected. This class cannot be inherited.</p>\n"
  remarks: "\n<p>\n<strong>TargetParameterCountException</strong> uses the HRESULT COR_E_TARGETPARAMCOUNT which has the value 0x8002000E.</p>\n"
  syntax:
    content: 'public sealed class TargetParameterCountException : Exception'
    content.vb: >-
      Public NotInheritable Class TargetParameterCountException
          Inherits Exception
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: System.Reflection.TargetParameterCountException.#ctor
  commentId: M:System.Reflection.TargetParameterCountException.#ctor
  id: '#ctor'
  parent: System.Reflection.TargetParameterCountException
  langs:
  - csharp
  - vb
  name: TargetParameterCountException()
  fullName: System.Reflection.TargetParameterCountException.TargetParameterCountException()
  type: Constructor
  source:
    remote:
      path: src/System.Reflection/ref/4.0/System.Reflection.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Reflection/ref/4.0/System.Reflection.cs
    startLine: 275
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Reflection.TargetParameterCountException\" data-throw-if-not-resolved=\"false\"></xref> class with an empty message string and the root cause of the exception.</p>\n"
  remarks: "\n<p>\n<strong>TargetParameterCountException</strong> inherits from <xref href=\"System.Exception\" data-throw-if-not-resolved=\"false\"></xref>. This constructor sets the properties of the Exception object as shown in the following table.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>\n</p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The empty string (\"\"). </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public TargetParameterCountException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Reflection.TargetParameterCountException.#ctor(System.String)
  commentId: M:System.Reflection.TargetParameterCountException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Reflection.TargetParameterCountException
  langs:
  - csharp
  - vb
  name: TargetParameterCountException(String)
  fullName: System.Reflection.TargetParameterCountException.TargetParameterCountException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Reflection/ref/4.0/System.Reflection.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Reflection/ref/4.0/System.Reflection.cs
    startLine: 276
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Reflection.TargetParameterCountException\" data-throw-if-not-resolved=\"false\"></xref> class with its message string set to the given message and the root cause exception.</p>\n"
  remarks: "\n<p>\n<strong>TargetParmeterCountException</strong> inherits from <xref href=\"System.Exception\" data-throw-if-not-resolved=\"false\"></xref>. This constructor sets the properties of the <strong>Exception</strong> object as shown in the following table.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>\n</p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public TargetParameterCountException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>A <strong>String</strong> describing the reason this exception was thrown. </p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Reflection.TargetParameterCountException.#ctor(System.String,System.Exception)
  commentId: M:System.Reflection.TargetParameterCountException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Reflection.TargetParameterCountException
  langs:
  - csharp
  - vb
  name: TargetParameterCountException(String, Exception)
  fullName: System.Reflection.TargetParameterCountException.TargetParameterCountException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Reflection/ref/4.0/System.Reflection.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Reflection/ref/4.0/System.Reflection.cs
    startLine: 277
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Reflection.TargetParameterCountException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n"
  remarks: "\n<p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property. The <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property returns the same value that is passed into the constructor, or <strong>null</strong> if the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property does not supply the inner exception value to the constructor.</p>\n<p>The following table shows the initial property values for an instance of <xref href=\"System.Reflection.TargetParameterCountException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The inner exception reference. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The error message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public TargetParameterCountException(string message, Exception inner)
    content.vb: Public Sub New(message As String, inner As Exception)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The error message that explains the reason for the exception. </p>\n"
    - id: inner
      type: System.Exception
      description: "\n<p>The exception that is the cause of the current exception. If the <em>inner</em> parameter is not <strong>null</strong>, the current exception is raised in a <strong>catch</strong> block that handles the inner exception. </p>\n"
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Reflection
  isExternal: false
  name: System.Reflection
  fullName: System.Reflection
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
