items:
- uid: System.Threading.Tasks.TaskSchedulerException
  commentId: T:System.Threading.Tasks.TaskSchedulerException
  id: TaskSchedulerException
  parent: System.Threading.Tasks
  children:
  - System.Threading.Tasks.TaskSchedulerException.#ctor
  - System.Threading.Tasks.TaskSchedulerException.#ctor(System.Exception)
  - System.Threading.Tasks.TaskSchedulerException.#ctor(System.String)
  - System.Threading.Tasks.TaskSchedulerException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: TaskSchedulerException
  fullName: System.Threading.Tasks.TaskSchedulerException
  type: Class
  source:
    remote:
      path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: TaskSchedulerException
    path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
    startLine: 544
  assemblies:
  - System.Threading.Tasks
  namespace: System.Threading.Tasks
  summary: "\n<p>Represents an exception used to communicate an invalid operation by a <xref href=\"System.Threading.Tasks.TaskScheduler\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n"
  syntax:
    content: 'public class TaskSchedulerException : Exception'
    content.vb: >-
      Public Class TaskSchedulerException
          Inherits Exception
  seealso:
  - type: System.Threading.Tasks.TaskScheduler
    commentId: T:System.Threading.Tasks.TaskScheduler
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Threading.Tasks.TaskSchedulerException.#ctor
  commentId: M:System.Threading.Tasks.TaskSchedulerException.#ctor
  id: '#ctor'
  parent: System.Threading.Tasks.TaskSchedulerException
  langs:
  - csharp
  - vb
  name: TaskSchedulerException()
  fullName: System.Threading.Tasks.TaskSchedulerException.TaskSchedulerException()
  type: Constructor
  source:
    remote:
      path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
    startLine: 546
  assemblies:
  - System.Threading.Tasks
  namespace: System.Threading.Tasks
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Threading.Tasks.TaskSchedulerException\" data-throw-if-not-resolved=\"false\"></xref> class with a system-supplied message that describes the error.</p>\n"
  remarks: "\n<p>This constructor initializes the <xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref> property of the new instance to a system-supplied message that describes the error, such as \"DefaultMessageDisplayedByParameterlessCtorWriterMustSupply\" This message takes into account the current system culture.</p>\n<p>The following table shows the initial property values for an instance of <xref href=\"System.Threading.Tasks.TaskSchedulerException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>.</p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The localized error message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public TaskSchedulerException()
    content.vb: Public Sub New
  seealso:
  - type: System.Threading.Tasks.TaskScheduler
    commentId: T:System.Threading.Tasks.TaskScheduler
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Threading.Tasks.TaskSchedulerException.#ctor(System.Exception)
  commentId: M:System.Threading.Tasks.TaskSchedulerException.#ctor(System.Exception)
  id: '#ctor(System.Exception)'
  parent: System.Threading.Tasks.TaskSchedulerException
  langs:
  - csharp
  - vb
  name: TaskSchedulerException(Exception)
  fullName: System.Threading.Tasks.TaskSchedulerException.TaskSchedulerException(System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
    startLine: 547
  assemblies:
  - System.Threading.Tasks
  namespace: System.Threading.Tasks
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Threading.Tasks.TaskSchedulerException\" data-throw-if-not-resolved=\"false\"></xref> class using the default error message and a reference to the inner exception that is the cause of this exception.</p>\n"
  example:
  - 
  syntax:
    content: public TaskSchedulerException(Exception innerException)
    content.vb: Public Sub New(innerException As Exception)
    parameters:
    - id: innerException
      type: System.Exception
      description: "\n<p>The exception that is the cause of the current exception.</p>\n"
  seealso:
  - type: System.Threading.Tasks.TaskScheduler
    commentId: T:System.Threading.Tasks.TaskScheduler
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Threading.Tasks.TaskSchedulerException.#ctor(System.String)
  commentId: M:System.Threading.Tasks.TaskSchedulerException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Threading.Tasks.TaskSchedulerException
  langs:
  - csharp
  - vb
  name: TaskSchedulerException(String)
  fullName: System.Threading.Tasks.TaskSchedulerException.TaskSchedulerException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
    startLine: 548
  assemblies:
  - System.Threading.Tasks
  namespace: System.Threading.Tasks
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Threading.Tasks.TaskSchedulerException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified message that describes the error.</p>\n"
  remarks: "\n<p>The following table shows the initial property values for an instance of <xref href=\"System.Threading.Tasks.TaskSchedulerException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>.</p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The error message string specified in <em>message</em>. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public TaskSchedulerException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</p>\n"
  seealso:
  - type: System.Threading.Tasks.TaskScheduler
    commentId: T:System.Threading.Tasks.TaskScheduler
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Threading.Tasks.TaskSchedulerException.#ctor(System.String,System.Exception)
  commentId: M:System.Threading.Tasks.TaskSchedulerException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Threading.Tasks.TaskSchedulerException
  langs:
  - csharp
  - vb
  name: TaskSchedulerException(String, Exception)
  fullName: System.Threading.Tasks.TaskSchedulerException.TaskSchedulerException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
    startLine: 549
  assemblies:
  - System.Threading.Tasks
  namespace: System.Threading.Tasks
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Threading.Tasks.TaskSchedulerException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n"
  remarks: "\n<p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property. The <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property returns the same value that is passed into the constructor, or <strong>null</strong> if the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property does not supply the inner exception value to the constructor.</p>\n<p>The following table shows the initial property values for an instance of <xref href=\"System.Threading.Tasks.TaskSchedulerException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The error message string specified in <em>message</em>. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public TaskSchedulerException(string message, Exception innerException)
    content.vb: Public Sub New(message As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture. </p>\n"
    - id: innerException
      type: System.Exception
      description: "\n<p>The exception that is the cause of the current exception. If the <em>innerException</em> parameter is not <strong>null</strong>, the current exception is raised in a <strong>catch</strong> block that handles the inner exception. </p>\n"
  seealso:
  - type: System.Threading.Tasks.TaskScheduler
    commentId: T:System.Threading.Tasks.TaskScheduler
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Threading.Tasks
  isExternal: false
  name: System.Threading.Tasks
  fullName: System.Threading.Tasks
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
