items:
- uid: System.Threading.SynchronizationLockException
  commentId: T:System.Threading.SynchronizationLockException
  id: SynchronizationLockException
  parent: System.Threading
  children:
  - System.Threading.SynchronizationLockException.#ctor
  - System.Threading.SynchronizationLockException.#ctor(System.String)
  - System.Threading.SynchronizationLockException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: SynchronizationLockException
  fullName: System.Threading.SynchronizationLockException
  type: Class
  source:
    remote:
      path: src/System.Threading/ref/System.Threading.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: SynchronizationLockException
    path: src/System.Threading/ref/System.Threading.cs
    startLine: 321
  assemblies:
  - System.Threading
  namespace: System.Threading
  summary: "\n<p>The exception that is thrown when a method requires the caller to own the lock on a given Monitor, and the method is invoked by a caller that does not own that lock.</p>\n"
  remarks: "\n<p>\n<xref href=\"System.Threading.SynchronizationLockException\" data-throw-if-not-resolved=\"false\"></xref> is thrown by calling the <xref href=\"System.Threading.Monitor.Exit(System.Object)\" data-throw-if-not-resolved=\"false\"></xref>, <xref href=\"System.Threading.Monitor.Pulse(System.Object)\" data-throw-if-not-resolved=\"false\"></xref>, <xref href=\"System.Threading.Monitor.PulseAll(System.Object)\" data-throw-if-not-resolved=\"false\"></xref>, and <xref href=\"System.Threading.Monitor.Wait(System.Object,System.Int32,System.Boolean)\" data-throw-if-not-resolved=\"false\"></xref> methods of the <xref href=\"System.Threading.Monitor\" data-throw-if-not-resolved=\"false\"></xref> class from an unsynchronized block of code.</p>\n<p>\n<xref href=\"System.Threading.SynchronizationLockException\" data-throw-if-not-resolved=\"false\"></xref> uses the HRESULT COR_E_SYNCHRONIZATIONLOCK, which has the value 0x80131518.</p>\n<p>For a list of initial property values for an instance of <xref href=\"System.Threading.SynchronizationLockException\" data-throw-if-not-resolved=\"false\"></xref>, see the <xref href=\"System.Threading.SynchronizationLockException.#ctor\" data-throw-if-not-resolved=\"false\"></xref> constructors.</p>\n"
  syntax:
    content: 'public class SynchronizationLockException : Exception'
    content.vb: >-
      Public Class SynchronizationLockException
          Inherits Exception
  seealso:
  - type: System.Threading.Monitor
    commentId: T:System.Threading.Monitor
  - type: System.Exception
    commentId: T:System.Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Threading.SynchronizationLockException.#ctor
  commentId: M:System.Threading.SynchronizationLockException.#ctor
  id: '#ctor'
  parent: System.Threading.SynchronizationLockException
  langs:
  - csharp
  - vb
  name: SynchronizationLockException()
  fullName: System.Threading.SynchronizationLockException.SynchronizationLockException()
  type: Constructor
  source:
    remote:
      path: src/System.Threading/ref/System.Threading.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Threading/ref/System.Threading.cs
    startLine: 323
  assemblies:
  - System.Threading
  namespace: System.Threading
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Threading.SynchronizationLockException\" data-throw-if-not-resolved=\"false\"></xref> class with default properties.</p>\n"
  remarks: "\n<p>The following table shows the initial property values for an instance of <xref href=\"System.Threading.SynchronizationLockException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The localized error message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public SynchronizationLockException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Threading.SynchronizationLockException.#ctor(System.String)
  commentId: M:System.Threading.SynchronizationLockException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Threading.SynchronizationLockException
  langs:
  - csharp
  - vb
  name: SynchronizationLockException(String)
  fullName: System.Threading.SynchronizationLockException.SynchronizationLockException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Threading/ref/System.Threading.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Threading/ref/System.Threading.cs
    startLine: 324
  assemblies:
  - System.Threading
  namespace: System.Threading
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Threading.SynchronizationLockException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified error message.</p>\n"
  remarks: "\n<p>The following table shows the initial property values for an instance of <xref href=\"System.Threading.SynchronizationLockException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The error message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public SynchronizationLockException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The error message that explains the reason for the exception. </p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Threading.SynchronizationLockException.#ctor(System.String,System.Exception)
  commentId: M:System.Threading.SynchronizationLockException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Threading.SynchronizationLockException
  langs:
  - csharp
  - vb
  name: SynchronizationLockException(String, Exception)
  fullName: System.Threading.SynchronizationLockException.SynchronizationLockException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Threading/ref/System.Threading.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Threading/ref/System.Threading.cs
    startLine: 325
  assemblies:
  - System.Threading
  namespace: System.Threading
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Threading.SynchronizationLockException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n"
  remarks: "\n<p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property. The <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property returns the same value that is passed into the constructor, or <strong>null</strong> if the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property does not supply the inner exception value to the constructor.</p>\n<p>The following table shows the initial property values for an instance of <xref href=\"System.Threading.SynchronizationLockException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The inner exception reference. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The error message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public SynchronizationLockException(string message, Exception innerException)
    content.vb: Public Sub New(message As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The error message that explains the reason for the exception. </p>\n"
    - id: innerException
      type: System.Exception
      description: "\n<p>The exception that is the cause of the current exception. If the <em>innerException</em> parameter is not <strong>null</strong>, the current exception is raised in a <strong>catch</strong> block that handles the inner exception. </p>\n"
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Threading
  isExternal: false
  name: System.Threading
  fullName: System.Threading
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
