items:
- uid: System.Runtime.InteropServices.SafeArrayRankMismatchException
  commentId: T:System.Runtime.InteropServices.SafeArrayRankMismatchException
  id: SafeArrayRankMismatchException
  parent: System.Runtime.InteropServices
  children:
  - System.Runtime.InteropServices.SafeArrayRankMismatchException.#ctor
  - System.Runtime.InteropServices.SafeArrayRankMismatchException.#ctor(System.String)
  - System.Runtime.InteropServices.SafeArrayRankMismatchException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: SafeArrayRankMismatchException
  fullName: System.Runtime.InteropServices.SafeArrayRankMismatchException
  type: Class
  source:
    remote:
      path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: SafeArrayRankMismatchException
    path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
    startLine: 687
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: "\n<p>The exception thrown when the rank of an incoming <strong>SAFEARRAY</strong> does not match the rank specified in the managed signature.</p>\n"
  remarks: "\n<p>\n<strong>SafeArrayRankMismatchException</strong> uses the HRESULT COR_E_SAFEARRAYRANKMISMATCH which has the value 0x80131538.</p>\n<p>The rank of a <strong>SAFEARRAY</strong> is the number of dimensions in that array.</p>\n"
  syntax:
    content: 'public class SafeArrayRankMismatchException : Exception'
    content.vb: >-
      Public Class SafeArrayRankMismatchException
          Inherits Exception
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Runtime.InteropServices.SafeArrayRankMismatchException.#ctor
  commentId: M:System.Runtime.InteropServices.SafeArrayRankMismatchException.#ctor
  id: '#ctor'
  parent: System.Runtime.InteropServices.SafeArrayRankMismatchException
  langs:
  - csharp
  - vb
  name: SafeArrayRankMismatchException()
  fullName: System.Runtime.InteropServices.SafeArrayRankMismatchException.SafeArrayRankMismatchException()
  type: Constructor
  source:
    remote:
      path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
    startLine: 689
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: "\n<p>Initializes a new instance of the <strong>SafeArrayTypeMismatchException</strong> class with default values.</p>\n"
  remarks: "\n<p>\n<strong>SafeArrayRankMismatchException</strong> inherits from <xref href=\"System.SystemException\" data-throw-if-not-resolved=\"false\"></xref>. This constructor sets the properties of the <xref href=\"System.Exception\" data-throw-if-not-resolved=\"false\"></xref> object as shown in the following table.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>A localized error message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public SafeArrayRankMismatchException()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Runtime.InteropServices.SafeArrayRankMismatchException.#ctor(System.String)
  commentId: M:System.Runtime.InteropServices.SafeArrayRankMismatchException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.InteropServices.SafeArrayRankMismatchException
  langs:
  - csharp
  - vb
  name: SafeArrayRankMismatchException(String)
  fullName: System.Runtime.InteropServices.SafeArrayRankMismatchException.SafeArrayRankMismatchException(System.String)
  type: Constructor
  source:
    remote:
      path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
    startLine: 690
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: "\n<p>Initializes a new instance of the <strong>SafeArrayRankMismatchException</strong> class with the specified message.</p>\n"
  remarks: "\n<p>\n<strong>SafeArrayRankMismatchException</strong> inherits from <xref href=\"System.SystemException\" data-throw-if-not-resolved=\"false\"></xref>. This constructor sets the properties of the <xref href=\"System.Exception\" data-throw-if-not-resolved=\"false\"></xref> object as shown in the following table.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<strong>null</strong>. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>\n<em>message</em>\n</p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public SafeArrayRankMismatchException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The message that indicates the reason for the exception. </p>\n"
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Runtime.InteropServices.SafeArrayRankMismatchException.#ctor(System.String,System.Exception)
  commentId: M:System.Runtime.InteropServices.SafeArrayRankMismatchException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.InteropServices.SafeArrayRankMismatchException
  langs:
  - csharp
  - vb
  name: SafeArrayRankMismatchException(String, Exception)
  fullName: System.Runtime.InteropServices.SafeArrayRankMismatchException.SafeArrayRankMismatchException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
    startLine: 691
  assemblies:
  - System.Runtime.InteropServices
  namespace: System.Runtime.InteropServices
  summary: "\n<p>Initializes a new instance of the <xref href=\"System.Runtime.InteropServices.SafeArrayRankMismatchException\" data-throw-if-not-resolved=\"false\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n"
  remarks: "\n<p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property. The <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property returns the same value that is passed into the constructor, or <strong>null</strong> if the <xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref> property does not supply the inner exception value to the constructor.</p>\n<p>The following table shows the initial property values for an instance of <xref href=\"System.Runtime.InteropServices.SafeArrayRankMismatchException\" data-throw-if-not-resolved=\"false\"></xref>.</p>\n<p>Property </p>\n<p>Value </p>\n<table><tbody><tr><td>\n<p>\n<xref href=\"System.Exception.InnerException\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The inner exception reference. </p>\n</td></tr><tr><td>\n<p>\n<xref href=\"System.Exception.Message\" data-throw-if-not-resolved=\"false\"></xref>\n</p>\n</td><td>\n<p>The error message string. </p>\n</td></tr></tbody></table>\n"
  syntax:
    content: public SafeArrayRankMismatchException(string message, Exception inner)
    content.vb: Public Sub New(message As String, inner As Exception)
    parameters:
    - id: message
      type: System.String
      description: "\n<p>The error message that explains the reason for the exception. </p>\n"
    - id: inner
      type: System.Exception
      description: "\n<p>The exception that is the cause of the current exception. If the <em>inner</em> parameter is not <strong>null</strong>, the current exception is raised in a <strong>catch</strong> block that handles the inner exception. </p>\n"
  seealso:
  - type: System.Exception
    commentId: T:System.Exception
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Runtime.InteropServices
  isExternal: false
  name: System.Runtime.InteropServices
  fullName: System.Runtime.InteropServices
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
