items:
- uid: System.Reflection.TargetInvocationException
  commentId: T:System.Reflection.TargetInvocationException
  id: TargetInvocationException
  parent: System.Reflection
  children:
  - System.Reflection.TargetInvocationException.#ctor(System.Exception)
  - System.Reflection.TargetInvocationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: TargetInvocationException
  fullName: System.Reflection.TargetInvocationException
  type: Class
  source:
    remote:
      path: src/mscorlib/src/System/Reflection/TargetInvocationException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: TargetInvocationException
    path: src/mscorlib/src/System/Reflection/TargetInvocationException.cs
    startLine: 19
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: The exception that is thrown by methods invoked through reflection. This class cannot be inherited.
  syntax:
    content: 'public sealed class TargetInvocationException : Exception'
    content.vb: >-
      Public NotInheritable Class TargetInvocationException
          Inherits Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: System.Reflection.TargetInvocationException.#ctor(System.Exception)
  commentId: M:System.Reflection.TargetInvocationException.#ctor(System.Exception)
  id: '#ctor(System.Exception)'
  parent: System.Reflection.TargetInvocationException
  langs:
  - csharp
  - vb
  name: TargetInvocationException(Exception)
  fullName: System.Reflection.TargetInvocationException.TargetInvocationException(System.Exception)
  type: Constructor
  source:
    remote:
      path: src/mscorlib/src/System/Reflection/TargetInvocationException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: .ctor
    path: src/mscorlib/src/System/Reflection/TargetInvocationException.cs
    startLine: 38
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: Initializes a new instance of the <xref href="System.Reflection.TargetInvocationException" data-throw-if-not-resolved="false"></xref> class with a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public TargetInvocationException(Exception inner)
    content.vb: Public Sub New(inner As Exception)
    parameters:
    - id: inner
      type: System.Exception
      description: 'The exception that is the cause of the current exception. If the <em>inner</em> parameter is not null, the current exception is raised in a catch block that handles the inner exception. '
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Reflection.TargetInvocationException.#ctor(System.String,System.Exception)
  commentId: M:System.Reflection.TargetInvocationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Reflection.TargetInvocationException
  langs:
  - csharp
  - vb
  name: TargetInvocationException(String, Exception)
  fullName: System.Reflection.TargetInvocationException.TargetInvocationException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/mscorlib/src/System/Reflection/TargetInvocationException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: .ctor
    path: src/mscorlib/src/System/Reflection/TargetInvocationException.cs
    startLine: 43
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: Initializes a new instance of the <xref href="System.Reflection.TargetInvocationException" data-throw-if-not-resolved="false"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public TargetInvocationException(string message, Exception inner)
    content.vb: Public Sub New(message As String, inner As Exception)
    parameters:
    - id: message
      type: System.String
      description: 'The error message that explains the reason for the exception. '
    - id: inner
      type: System.Exception
      description: 'The exception that is the cause of the current exception. If the <em>inner</em> parameter is not null, the current exception is raised in a catch block that handles the inner exception. '
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Reflection
  isExternal: false
  name: System.Reflection
  fullName: System.Reflection
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
